server:
  port: 9092

spring:
  application:
    name: food-service

  datasource:
    url: jdbc:mysql://localhost:3306/foodservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true   # change to false in production



# Actuator & Info
management:
  endpoints:
    web:
      exposure:
        include: "*"   # exposes all actuator endpoints
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# App Info (for /actuator/info)
info:
  app:
    name: Food Service
    description: Handles food-related operations in FastFeast
    version: 1.0.0

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
